# Generated by Django 5.1.4 on 2025-02-22 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibra_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('exponent', models.IntegerField()),
            ],
            options={
                'db_table': 'unit_prefixes',
            },
        ),
        migrations.AddField(
            model_name='measurement',
            name='parameter',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='unit4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='prefix1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefix1', to='calibra_api.unitprefix'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='prefix2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefix2', to='calibra_api.unitprefix'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='prefix3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefix3', to='calibra_api.unitprefix'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='prefix4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefix4', to='calibra_api.unitprefix'),
        ),
    ]
