# Generated by Django 5.1.4 on 2025-02-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibra_api', '0002_unitprefix_measurement_parameter_measurement_unit4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitprefix',
            name='symbol',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=10, unique=True),
        ),
    ]
