# Generated by Django 5.1.4 on 2025-02-22 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibra_api', '0003_alter_unitprefix_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='prefix1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefix1', to='calibra_api.unitprefix', to_field='symbol'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='prefix2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefix2', to='calibra_api.unitprefix', to_field='symbol'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='prefix3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefix3', to='calibra_api.unitprefix', to_field='symbol'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='prefix4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefix4', to='calibra_api.unitprefix', to_field='symbol'),
        ),
    ]
