# Generated by Django 5.1.6 on 2025-03-21 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibra_api', '0004_alter_measurement_prefix1_alter_measurement_prefix2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitPrefix',
            new_name='Prefix',
        ),
        migrations.AddField(
            model_name='measurement',
            name='prefix5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefix5', to='calibra_api.prefix', to_field='symbol'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='unit5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
